version: '3.7'
services:
  vespa:
    image: vespaengine/vespa
    hostname: pintxo-engine
    ports:
      - "8080:8080"
      - "19071:19071"
    # volumes:
    #   - ./vespa-init.sh:/home/newera/pintxo-dev/pintxo-data-weaver/vespa-init.sh
    # entrypoint: ["/home/newera/pintxo-dev/pintxo-data-weaver/vespa-init.sh"]
    networks:
      - pintxo-network

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - pintxo-network

  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKAJS_NO_PARTITIONER_WARNING: 1
    ports:
      - "9092:9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - pintxo-network
  
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
    depends_on:
      - "kafka"
    networks:
      - pintxo-network

  pintxo-engine-connector:
    build: ./pintxo-engine-connector
    depends_on:
      - vespa
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
    ports:
      - "4003:4003"
    networks:
      - pintxo-network

  # substreams-service:
  #   build: ./substreams-service
  #   depends_on:
  #     - vespa
  #     - kafka
  #   environment:
  #     KAFKA_BROKER: kafka:9092
  #   ports:
  #     - "4000:4000"
  #   networks:
  #     - pintxo-network

  # pyth-service:
  #   build: ./pyth-service
  #   depends_on:
  #     - vespa
  #     - kafka
  #   environment:
  #     KAFKA_BROKER: kafka:9092
  #   ports:
  #     - "4001:4001"
  #   networks:
  #     - pintxo-network

  api-service:
    build: ./api-service
    depends_on:
      - vespa
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
    ports:
      - "4002:4002"
    networks:
      - pintxo-network

networks:
  pintxo-network:
    name: pintxo-network
    driver: bridge